using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class InstrucBlink : MonoBehaviour
{
    public GameObject title;
    void Start()
    {
        StartCoroutine(Paragraph());
    }

    // Update is called once per frame
    IEnumerator Paragraph(){
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
        yield return new WaitForSeconds(1);
        title.SetActive(false);
        yield return new WaitForSeconds(.3f);
        title.SetActive(true);
    }
}